### ISSUE TITLE
Travis integration

### ISSUE THREAD

**Issue by sageahn** [sageahn/acceleratedcpp#3]
https://svn.boost.org/trac/boost/wiki/TravisCoverals
이것도 재밌겠네요.

**Comment by jinwoo-jeon0** [comment]
CI인가요?
CI, https://en.m.wikipedia.org/wiki/Build_verification_test, 등등 있으면 개발하긴
편하죠.
없으면 원시인과 공감할 수 있습니다. :)

**Comment by sageahn** [comment]
ㅎㅎ 네 CI죠. 이 리포는 머랄까 앞으로 할 것들의 보일러플래이트 같은 것이 되지 않을까 싶어서요

**Comment by sageahn** [comment]
https://travis-ci.org/ 에 리포 등록만 했더니 벌써 push에 fail 메시지 나오네요 ㅎㅎ .travis.yml을 얼른 만들어야 ㅋㅋㅋ

**Comment by sageahn** [comment]
https://coveralls.io/

**Comment by jinwoo-jeon0** [comment]
.travis.yml 추가했습니다.
coverall은 issue를 분리해서 처리해보죠.
